// flow-typed signature: e015848ac65e2fbd6ece64e3b081160d
// flow-typed version: <<STUB>>/jss-extend_v6.2.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jss-extend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jss-extend' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jss-extend/dist/jss-extend' {
  declare module.exports: any;
}

declare module 'jss-extend/dist/jss-extend.min' {
  declare module.exports: any;
}

declare module 'jss-extend/karma.conf' {
  declare module.exports: any;
}

declare module 'jss-extend/lib/index' {
  declare module.exports: any;
}

declare module 'jss-extend/lib/index.test' {
  declare module.exports: any;
}

declare module 'jss-extend/tests.webpack' {
  declare module.exports: any;
}

declare module 'jss-extend/tests/index' {
  declare module.exports: any;
}

declare module 'jss-extend/tests/index.test' {
  declare module.exports: any;
}

declare module 'jss-extend/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jss-extend/dist/jss-extend.js' {
  declare module.exports: $Exports<'jss-extend/dist/jss-extend'>;
}
declare module 'jss-extend/dist/jss-extend.min.js' {
  declare module.exports: $Exports<'jss-extend/dist/jss-extend.min'>;
}
declare module 'jss-extend/karma.conf.js' {
  declare module.exports: $Exports<'jss-extend/karma.conf'>;
}
declare module 'jss-extend/lib/index.js' {
  declare module.exports: $Exports<'jss-extend/lib/index'>;
}
declare module 'jss-extend/lib/index.test.js' {
  declare module.exports: $Exports<'jss-extend/lib/index.test'>;
}
declare module 'jss-extend/tests.webpack.js' {
  declare module.exports: $Exports<'jss-extend/tests.webpack'>;
}
declare module 'jss-extend/tests/index.js' {
  declare module.exports: $Exports<'jss-extend/tests/index'>;
}
declare module 'jss-extend/tests/index.test.js' {
  declare module.exports: $Exports<'jss-extend/tests/index.test'>;
}
declare module 'jss-extend/webpack.config.js' {
  declare module.exports: $Exports<'jss-extend/webpack.config'>;
}
