// flow-typed signature: 27732d09424e3151f75d8a7b469a4bd9
// flow-typed version: <<STUB>>/micro-memoize_v2.0.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'micro-memoize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'micro-memoize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'micro-memoize/benchmark/addy-osmani' {
  declare module.exports: any;
}

declare module 'micro-memoize/benchmark/index' {
  declare module.exports: any;
}

declare module 'micro-memoize/dist/micro-memoize' {
  declare module.exports: any;
}

declare module 'micro-memoize/dist/micro-memoize.min' {
  declare module.exports: any;
}

declare module 'micro-memoize/es/index' {
  declare module.exports: any;
}

declare module 'micro-memoize/es/types' {
  declare module.exports: any;
}

declare module 'micro-memoize/es/utils' {
  declare module.exports: any;
}

declare module 'micro-memoize/flow-typed/micro-memoize' {
  declare module.exports: any;
}

declare module 'micro-memoize/lib/index' {
  declare module.exports: any;
}

declare module 'micro-memoize/lib/types' {
  declare module.exports: any;
}

declare module 'micro-memoize/lib/utils' {
  declare module.exports: any;
}

declare module 'micro-memoize/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'micro-memoize/benchmark/addy-osmani.js' {
  declare module.exports: $Exports<'micro-memoize/benchmark/addy-osmani'>;
}
declare module 'micro-memoize/benchmark/index.js' {
  declare module.exports: $Exports<'micro-memoize/benchmark/index'>;
}
declare module 'micro-memoize/dist/micro-memoize.js' {
  declare module.exports: $Exports<'micro-memoize/dist/micro-memoize'>;
}
declare module 'micro-memoize/dist/micro-memoize.min.js' {
  declare module.exports: $Exports<'micro-memoize/dist/micro-memoize.min'>;
}
declare module 'micro-memoize/es/index.js' {
  declare module.exports: $Exports<'micro-memoize/es/index'>;
}
declare module 'micro-memoize/es/types.js' {
  declare module.exports: $Exports<'micro-memoize/es/types'>;
}
declare module 'micro-memoize/es/utils.js' {
  declare module.exports: $Exports<'micro-memoize/es/utils'>;
}
declare module 'micro-memoize/flow-typed/micro-memoize.js' {
  declare module.exports: $Exports<'micro-memoize/flow-typed/micro-memoize'>;
}
declare module 'micro-memoize/lib/index.js' {
  declare module.exports: $Exports<'micro-memoize/lib/index'>;
}
declare module 'micro-memoize/lib/types.js' {
  declare module.exports: $Exports<'micro-memoize/lib/types'>;
}
declare module 'micro-memoize/lib/utils.js' {
  declare module.exports: $Exports<'micro-memoize/lib/utils'>;
}
declare module 'micro-memoize/rollup.config.js' {
  declare module.exports: $Exports<'micro-memoize/rollup.config'>;
}
