// flow-typed signature: 098e45bf7506775339faa351ba78d20a
// flow-typed version: <<STUB>>/ory-editor-plugins-divider_vv0.2.27

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ory-editor-plugins-divider'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ory-editor-plugins-divider' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ory-editor-plugins-divider/lib/index' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-divider/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ory-editor-plugins-divider/lib/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-divider/lib/index'>;
}
declare module 'ory-editor-plugins-divider/src/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-divider/src/index'>;
}
