// flow-typed signature: cefa99659c5957b410f1f322c3c5e7e7
// flow-typed version: <<STUB>>/ory-editor-plugins-spacer_vv0.2.27

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ory-editor-plugins-spacer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ory-editor-plugins-spacer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ory-editor-plugins-spacer/lib/Component/index' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-spacer/lib/index' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-spacer/src/Component/index' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-spacer/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ory-editor-plugins-spacer/lib/Component/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-spacer/lib/Component/index'>;
}
declare module 'ory-editor-plugins-spacer/lib/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-spacer/lib/index'>;
}
declare module 'ory-editor-plugins-spacer/src/Component/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-spacer/src/Component/index'>;
}
declare module 'ory-editor-plugins-spacer/src/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-spacer/src/index'>;
}
