// flow-typed signature: a2928adf6fab139c612fccaa03c42e52
// flow-typed version: <<STUB>>/ory-editor-plugins-image_vv0.2.27

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ory-editor-plugins-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ory-editor-plugins-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ory-editor-plugins-image/lib/Component/common' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-image/lib/Component/Display/index' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-image/lib/Component/Form/index' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-image/lib/Component/index' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-image/lib/index' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-image/src/Component/common' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-image/src/Component/Display/index' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-image/src/Component/Form/index' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-image/src/Component/index' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-image/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ory-editor-plugins-image/lib/Component/common.js' {
  declare module.exports: $Exports<'ory-editor-plugins-image/lib/Component/common'>;
}
declare module 'ory-editor-plugins-image/lib/Component/Display/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-image/lib/Component/Display/index'>;
}
declare module 'ory-editor-plugins-image/lib/Component/Form/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-image/lib/Component/Form/index'>;
}
declare module 'ory-editor-plugins-image/lib/Component/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-image/lib/Component/index'>;
}
declare module 'ory-editor-plugins-image/lib/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-image/lib/index'>;
}
declare module 'ory-editor-plugins-image/src/Component/common.js' {
  declare module.exports: $Exports<'ory-editor-plugins-image/src/Component/common'>;
}
declare module 'ory-editor-plugins-image/src/Component/Display/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-image/src/Component/Display/index'>;
}
declare module 'ory-editor-plugins-image/src/Component/Form/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-image/src/Component/Form/index'>;
}
declare module 'ory-editor-plugins-image/src/Component/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-image/src/Component/index'>;
}
declare module 'ory-editor-plugins-image/src/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-image/src/index'>;
}
