// flow-typed signature: cbe4e043bda5f64ef7ae2b8bf6814f7b
// flow-typed version: <<STUB>>/ory-editor_vv0.2.27

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ory-editor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ory-editor' {
  declare module.exports: any;
}
