// flow-typed signature: a9512c9cb0c651c949ad6c5506920245
// flow-typed version: <<STUB>>/ory-editor-renderer_vv0.2.27

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ory-editor-renderer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ory-editor-renderer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ory-editor-renderer/lib/index' {
  declare module.exports: any;
}

declare module 'ory-editor-renderer/src/index' {
  declare module.exports: any;
}

declare module 'ory-editor-renderer/src/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ory-editor-renderer/lib/index.js' {
  declare module.exports: $Exports<'ory-editor-renderer/lib/index'>;
}
declare module 'ory-editor-renderer/src/index.js' {
  declare module.exports: $Exports<'ory-editor-renderer/src/index'>;
}
declare module 'ory-editor-renderer/src/index.test.js' {
  declare module.exports: $Exports<'ory-editor-renderer/src/index.test'>;
}
