// flow-typed signature: 3f292926ff35da3fe3120a5d22b6177b
// flow-typed version: <<STUB>>/ory-editor-plugins-video_vv0.2.27

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ory-editor-plugins-video'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ory-editor-plugins-video' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ory-editor-plugins-video/lib/Component/common' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-video/lib/Component/Display/index' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-video/lib/Component/Form/index' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-video/lib/Component/index' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-video/lib/index' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-video/src/Component/common' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-video/src/Component/Display/index' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-video/src/Component/Form/index' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-video/src/Component/index' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-video/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ory-editor-plugins-video/lib/Component/common.js' {
  declare module.exports: $Exports<'ory-editor-plugins-video/lib/Component/common'>;
}
declare module 'ory-editor-plugins-video/lib/Component/Display/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-video/lib/Component/Display/index'>;
}
declare module 'ory-editor-plugins-video/lib/Component/Form/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-video/lib/Component/Form/index'>;
}
declare module 'ory-editor-plugins-video/lib/Component/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-video/lib/Component/index'>;
}
declare module 'ory-editor-plugins-video/lib/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-video/lib/index'>;
}
declare module 'ory-editor-plugins-video/src/Component/common.js' {
  declare module.exports: $Exports<'ory-editor-plugins-video/src/Component/common'>;
}
declare module 'ory-editor-plugins-video/src/Component/Display/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-video/src/Component/Display/index'>;
}
declare module 'ory-editor-plugins-video/src/Component/Form/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-video/src/Component/Form/index'>;
}
declare module 'ory-editor-plugins-video/src/Component/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-video/src/Component/index'>;
}
declare module 'ory-editor-plugins-video/src/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-video/src/index'>;
}
