// flow-typed signature: d42c6ffb8fb7b0f9e45a4bbde0b7a3c3
// flow-typed version: <<STUB>>/ory-editor-plugins-html5-video_vv0.2.27

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ory-editor-plugins-html5-video'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ory-editor-plugins-html5-video' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ory-editor-plugins-html5-video/lib/Component/index' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-html5-video/lib/index' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-html5-video/src/Component/index' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-html5-video/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ory-editor-plugins-html5-video/lib/Component/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-html5-video/lib/Component/index'>;
}
declare module 'ory-editor-plugins-html5-video/lib/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-html5-video/lib/index'>;
}
declare module 'ory-editor-plugins-html5-video/src/Component/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-html5-video/src/Component/index'>;
}
declare module 'ory-editor-plugins-html5-video/src/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-html5-video/src/index'>;
}
