// flow-typed signature: f32dd77ab6f5c3c6e4c2e3993f2b64f4
// flow-typed version: <<STUB>>/ory-editor-plugins-default-native_vv0.2.27

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ory-editor-plugins-default-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ory-editor-plugins-default-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ory-editor-plugins-default-native/lib/index' {
  declare module.exports: any;
}

declare module 'ory-editor-plugins-default-native/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ory-editor-plugins-default-native/lib/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-default-native/lib/index'>;
}
declare module 'ory-editor-plugins-default-native/src/index.js' {
  declare module.exports: $Exports<'ory-editor-plugins-default-native/src/index'>;
}
