// flow-typed signature: e23b479067645671111f1250638ca0f8
// flow-typed version: <<STUB>>/apollo-upload-server_v4.0.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-upload-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-upload-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-upload-server/lib/errors' {
  declare module.exports: any;
}

declare module 'apollo-upload-server/lib/index' {
  declare module.exports: any;
}

declare module 'apollo-upload-server/lib/middleware' {
  declare module.exports: any;
}

declare module 'apollo-upload-server/lib/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-upload-server/lib/errors.js' {
  declare module.exports: $Exports<'apollo-upload-server/lib/errors'>;
}
declare module 'apollo-upload-server/lib/index.js' {
  declare module.exports: $Exports<'apollo-upload-server/lib/index'>;
}
declare module 'apollo-upload-server/lib/middleware.js' {
  declare module.exports: $Exports<'apollo-upload-server/lib/middleware'>;
}
declare module 'apollo-upload-server/lib/types.js' {
  declare module.exports: $Exports<'apollo-upload-server/lib/types'>;
}
