// flow-typed signature: 14ec365ff3d2a0c30d596bd866abb4af
// flow-typed version: <<STUB>>/graphql-import_v0.4.5

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-import' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-import/dist/definition' {
  declare module.exports: any;
}

declare module 'graphql-import/dist/index' {
  declare module.exports: any;
}

declare module 'graphql-import/dist/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-import/dist/definition.js' {
  declare module.exports: $Exports<'graphql-import/dist/definition'>;
}
declare module 'graphql-import/dist/index.js' {
  declare module.exports: $Exports<'graphql-import/dist/index'>;
}
declare module 'graphql-import/dist/index.test.js' {
  declare module.exports: $Exports<'graphql-import/dist/index.test'>;
}
