// flow-typed signature: ab2ae348d546f7c20be924b4fefdba6a
// flow-typed version: <<STUB>>/graphql-scalar-types_v1.0.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-scalar-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-scalar-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-scalar-types/dist/yarn-starter' {
  declare module.exports: any;
}

declare module 'graphql-scalar-types/dist/yarn-starter.min' {
  declare module.exports: any;
}

declare module 'graphql-scalar-types/es/base' {
  declare module.exports: any;
}

declare module 'graphql-scalar-types/es/boolean' {
  declare module.exports: any;
}

declare module 'graphql-scalar-types/es/date' {
  declare module.exports: any;
}

declare module 'graphql-scalar-types/es/index' {
  declare module.exports: any;
}

declare module 'graphql-scalar-types/es/number' {
  declare module.exports: any;
}

declare module 'graphql-scalar-types/es/string' {
  declare module.exports: any;
}

declare module 'graphql-scalar-types/es/utils' {
  declare module.exports: any;
}

declare module 'graphql-scalar-types/es/validate' {
  declare module.exports: any;
}

declare module 'graphql-scalar-types/lib/base' {
  declare module.exports: any;
}

declare module 'graphql-scalar-types/lib/boolean' {
  declare module.exports: any;
}

declare module 'graphql-scalar-types/lib/date' {
  declare module.exports: any;
}

declare module 'graphql-scalar-types/lib/index' {
  declare module.exports: any;
}

declare module 'graphql-scalar-types/lib/number' {
  declare module.exports: any;
}

declare module 'graphql-scalar-types/lib/string' {
  declare module.exports: any;
}

declare module 'graphql-scalar-types/lib/utils' {
  declare module.exports: any;
}

declare module 'graphql-scalar-types/lib/validate' {
  declare module.exports: any;
}

declare module 'graphql-scalar-types/src/base' {
  declare module.exports: any;
}

declare module 'graphql-scalar-types/src/boolean' {
  declare module.exports: any;
}

declare module 'graphql-scalar-types/src/date' {
  declare module.exports: any;
}

declare module 'graphql-scalar-types/src/index' {
  declare module.exports: any;
}

declare module 'graphql-scalar-types/src/number' {
  declare module.exports: any;
}

declare module 'graphql-scalar-types/src/string' {
  declare module.exports: any;
}

declare module 'graphql-scalar-types/src/utils' {
  declare module.exports: any;
}

declare module 'graphql-scalar-types/src/validate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-scalar-types/dist/yarn-starter.js' {
  declare module.exports: $Exports<'graphql-scalar-types/dist/yarn-starter'>;
}
declare module 'graphql-scalar-types/dist/yarn-starter.min.js' {
  declare module.exports: $Exports<'graphql-scalar-types/dist/yarn-starter.min'>;
}
declare module 'graphql-scalar-types/es/base.js' {
  declare module.exports: $Exports<'graphql-scalar-types/es/base'>;
}
declare module 'graphql-scalar-types/es/boolean.js' {
  declare module.exports: $Exports<'graphql-scalar-types/es/boolean'>;
}
declare module 'graphql-scalar-types/es/date.js' {
  declare module.exports: $Exports<'graphql-scalar-types/es/date'>;
}
declare module 'graphql-scalar-types/es/index.js' {
  declare module.exports: $Exports<'graphql-scalar-types/es/index'>;
}
declare module 'graphql-scalar-types/es/number.js' {
  declare module.exports: $Exports<'graphql-scalar-types/es/number'>;
}
declare module 'graphql-scalar-types/es/string.js' {
  declare module.exports: $Exports<'graphql-scalar-types/es/string'>;
}
declare module 'graphql-scalar-types/es/utils.js' {
  declare module.exports: $Exports<'graphql-scalar-types/es/utils'>;
}
declare module 'graphql-scalar-types/es/validate.js' {
  declare module.exports: $Exports<'graphql-scalar-types/es/validate'>;
}
declare module 'graphql-scalar-types/lib/base.js' {
  declare module.exports: $Exports<'graphql-scalar-types/lib/base'>;
}
declare module 'graphql-scalar-types/lib/boolean.js' {
  declare module.exports: $Exports<'graphql-scalar-types/lib/boolean'>;
}
declare module 'graphql-scalar-types/lib/date.js' {
  declare module.exports: $Exports<'graphql-scalar-types/lib/date'>;
}
declare module 'graphql-scalar-types/lib/index.js' {
  declare module.exports: $Exports<'graphql-scalar-types/lib/index'>;
}
declare module 'graphql-scalar-types/lib/number.js' {
  declare module.exports: $Exports<'graphql-scalar-types/lib/number'>;
}
declare module 'graphql-scalar-types/lib/string.js' {
  declare module.exports: $Exports<'graphql-scalar-types/lib/string'>;
}
declare module 'graphql-scalar-types/lib/utils.js' {
  declare module.exports: $Exports<'graphql-scalar-types/lib/utils'>;
}
declare module 'graphql-scalar-types/lib/validate.js' {
  declare module.exports: $Exports<'graphql-scalar-types/lib/validate'>;
}
declare module 'graphql-scalar-types/src/base.js' {
  declare module.exports: $Exports<'graphql-scalar-types/src/base'>;
}
declare module 'graphql-scalar-types/src/boolean.js' {
  declare module.exports: $Exports<'graphql-scalar-types/src/boolean'>;
}
declare module 'graphql-scalar-types/src/date.js' {
  declare module.exports: $Exports<'graphql-scalar-types/src/date'>;
}
declare module 'graphql-scalar-types/src/index.js' {
  declare module.exports: $Exports<'graphql-scalar-types/src/index'>;
}
declare module 'graphql-scalar-types/src/number.js' {
  declare module.exports: $Exports<'graphql-scalar-types/src/number'>;
}
declare module 'graphql-scalar-types/src/string.js' {
  declare module.exports: $Exports<'graphql-scalar-types/src/string'>;
}
declare module 'graphql-scalar-types/src/utils.js' {
  declare module.exports: $Exports<'graphql-scalar-types/src/utils'>;
}
declare module 'graphql-scalar-types/src/validate.js' {
  declare module.exports: $Exports<'graphql-scalar-types/src/validate'>;
}
