// flow-typed signature: d01cfac703227e68092b437407808f43
// flow-typed version: <<STUB>>/json-schema-ref-parser_v3.3.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json-schema-ref-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'json-schema-ref-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'json-schema-ref-parser/dist/ref-parser' {
  declare module.exports: any;
}

declare module 'json-schema-ref-parser/dist/ref-parser.min' {
  declare module.exports: any;
}

declare module 'json-schema-ref-parser/lib/bundle' {
  declare module.exports: any;
}

declare module 'json-schema-ref-parser/lib/dereference' {
  declare module.exports: any;
}

declare module 'json-schema-ref-parser/lib/index' {
  declare module.exports: any;
}

declare module 'json-schema-ref-parser/lib/options' {
  declare module.exports: any;
}

declare module 'json-schema-ref-parser/lib/parse' {
  declare module.exports: any;
}

declare module 'json-schema-ref-parser/lib/parsers/binary' {
  declare module.exports: any;
}

declare module 'json-schema-ref-parser/lib/parsers/json' {
  declare module.exports: any;
}

declare module 'json-schema-ref-parser/lib/parsers/text' {
  declare module.exports: any;
}

declare module 'json-schema-ref-parser/lib/parsers/yaml' {
  declare module.exports: any;
}

declare module 'json-schema-ref-parser/lib/pointer' {
  declare module.exports: any;
}

declare module 'json-schema-ref-parser/lib/ref' {
  declare module.exports: any;
}

declare module 'json-schema-ref-parser/lib/refs' {
  declare module.exports: any;
}

declare module 'json-schema-ref-parser/lib/resolve-external' {
  declare module.exports: any;
}

declare module 'json-schema-ref-parser/lib/resolvers/file' {
  declare module.exports: any;
}

declare module 'json-schema-ref-parser/lib/resolvers/http' {
  declare module.exports: any;
}

declare module 'json-schema-ref-parser/lib/util/debug' {
  declare module.exports: any;
}

declare module 'json-schema-ref-parser/lib/util/plugins' {
  declare module.exports: any;
}

declare module 'json-schema-ref-parser/lib/util/promise' {
  declare module.exports: any;
}

declare module 'json-schema-ref-parser/lib/util/url' {
  declare module.exports: any;
}

declare module 'json-schema-ref-parser/lib/util/yaml' {
  declare module.exports: any;
}

declare module 'json-schema-ref-parser/lib/validators/z-schema' {
  declare module.exports: any;
}

// Filename aliases
declare module 'json-schema-ref-parser/dist/ref-parser.js' {
  declare module.exports: $Exports<'json-schema-ref-parser/dist/ref-parser'>;
}
declare module 'json-schema-ref-parser/dist/ref-parser.min.js' {
  declare module.exports: $Exports<'json-schema-ref-parser/dist/ref-parser.min'>;
}
declare module 'json-schema-ref-parser/lib/bundle.js' {
  declare module.exports: $Exports<'json-schema-ref-parser/lib/bundle'>;
}
declare module 'json-schema-ref-parser/lib/dereference.js' {
  declare module.exports: $Exports<'json-schema-ref-parser/lib/dereference'>;
}
declare module 'json-schema-ref-parser/lib/index.js' {
  declare module.exports: $Exports<'json-schema-ref-parser/lib/index'>;
}
declare module 'json-schema-ref-parser/lib/options.js' {
  declare module.exports: $Exports<'json-schema-ref-parser/lib/options'>;
}
declare module 'json-schema-ref-parser/lib/parse.js' {
  declare module.exports: $Exports<'json-schema-ref-parser/lib/parse'>;
}
declare module 'json-schema-ref-parser/lib/parsers/binary.js' {
  declare module.exports: $Exports<'json-schema-ref-parser/lib/parsers/binary'>;
}
declare module 'json-schema-ref-parser/lib/parsers/json.js' {
  declare module.exports: $Exports<'json-schema-ref-parser/lib/parsers/json'>;
}
declare module 'json-schema-ref-parser/lib/parsers/text.js' {
  declare module.exports: $Exports<'json-schema-ref-parser/lib/parsers/text'>;
}
declare module 'json-schema-ref-parser/lib/parsers/yaml.js' {
  declare module.exports: $Exports<'json-schema-ref-parser/lib/parsers/yaml'>;
}
declare module 'json-schema-ref-parser/lib/pointer.js' {
  declare module.exports: $Exports<'json-schema-ref-parser/lib/pointer'>;
}
declare module 'json-schema-ref-parser/lib/ref.js' {
  declare module.exports: $Exports<'json-schema-ref-parser/lib/ref'>;
}
declare module 'json-schema-ref-parser/lib/refs.js' {
  declare module.exports: $Exports<'json-schema-ref-parser/lib/refs'>;
}
declare module 'json-schema-ref-parser/lib/resolve-external.js' {
  declare module.exports: $Exports<'json-schema-ref-parser/lib/resolve-external'>;
}
declare module 'json-schema-ref-parser/lib/resolvers/file.js' {
  declare module.exports: $Exports<'json-schema-ref-parser/lib/resolvers/file'>;
}
declare module 'json-schema-ref-parser/lib/resolvers/http.js' {
  declare module.exports: $Exports<'json-schema-ref-parser/lib/resolvers/http'>;
}
declare module 'json-schema-ref-parser/lib/util/debug.js' {
  declare module.exports: $Exports<'json-schema-ref-parser/lib/util/debug'>;
}
declare module 'json-schema-ref-parser/lib/util/plugins.js' {
  declare module.exports: $Exports<'json-schema-ref-parser/lib/util/plugins'>;
}
declare module 'json-schema-ref-parser/lib/util/promise.js' {
  declare module.exports: $Exports<'json-schema-ref-parser/lib/util/promise'>;
}
declare module 'json-schema-ref-parser/lib/util/url.js' {
  declare module.exports: $Exports<'json-schema-ref-parser/lib/util/url'>;
}
declare module 'json-schema-ref-parser/lib/util/yaml.js' {
  declare module.exports: $Exports<'json-schema-ref-parser/lib/util/yaml'>;
}
declare module 'json-schema-ref-parser/lib/validators/z-schema.js' {
  declare module.exports: $Exports<'json-schema-ref-parser/lib/validators/z-schema'>;
}
