// flow-typed signature: ce21c4405b4903dacada77e94923af87
// flow-typed version: <<STUB>>/node-request-by-swagger_v1.0.6

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-request-by-swagger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-request-by-swagger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-request-by-swagger/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-request-by-swagger/index' {
  declare module.exports: $Exports<'node-request-by-swagger'>;
}
declare module 'node-request-by-swagger/index.js' {
  declare module.exports: $Exports<'node-request-by-swagger'>;
}
declare module 'node-request-by-swagger/test/index.js' {
  declare module.exports: $Exports<'node-request-by-swagger/test/index'>;
}
