// flow-typed signature: d02cd7d7b525b6868e28bc672e3c94fe
// flow-typed version: <<STUB>>/npm-run-script_v0.0.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm-run-script'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm-run-script' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'npm-run-script/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'npm-run-script/lib/index.js' {
  declare module.exports: $Exports<'npm-run-script/lib/index'>;
}
